# Generated by Django 5.0.4 on 2024-05-11 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('slug', models.CharField(blank=True, max_length=150, null=True, verbose_name='slug')),
                ('body', models.TextField(verbose_name='Содержание')),
                ('image_preview', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('date_of_creation', models.DateTimeField(default=datetime.datetime(2024, 5, 11, 17, 25, 22, 323514), max_length=100, verbose_name='Дата создания')),
                ('publication_sign', models.BooleanField(default=True, verbose_name='Публикация')),
                ('views_count', models.IntegerField(default=0, verbose_name='Просмотры')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
            },
        ),
    ]
