# Generated by Django 5.0.4 on 2024-05-12 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 12, 12, 52, 34, 72199), max_length=100, verbose_name='Дата создания'),
        ),
    ]
