# Generated by Django 5.0.4 on 2024-05-13 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_date_of_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 13, 19, 10, 24, 35595), max_length=100, verbose_name='Дата создания'),
        ),
    ]
