# Generated by Django 5.0.4 on 2024-05-11 09:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='Почта')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='MessageMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_line', models.CharField(max_length=150, verbose_name='Тема письма')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Текс сообщения')),
            ],
            options={
                'verbose_name': 'Сообщение рассылки',
                'verbose_name_plural': 'Сообщения рассылки',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=datetime.datetime(2024, 5, 11, 17, 25, 22, 322514), verbose_name='Дата и время первой отправки рассылки')),
                ('period_mailing', models.CharField(choices=[('Раз в день', 'Раз в день'), ('Раз в неделю', 'Раз в неделю'), ('Раз в месяц', 'Раз в месяц')], max_length=50, verbose_name='Периодичность рассылки')),
                ('status_mailing', models.CharField(choices=[('Запущена', 'Запущена'), ('Создана', 'Создана'), ('Завершена', 'Завершена')], max_length=50, verbose_name='Статус рассылки ')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.clientservice', verbose_name='Клиенты рассылки')),
                ('message', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.messagemailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='MailingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_last_mailing', models.DateField(auto_now_add=True, verbose_name='Дата и время последней рассылки')),
                ('status_mailing', models.BooleanField(verbose_name='Статус рассылки')),
                ('server_response', models.CharField(blank=True, null=True, verbose_name='Ответ почтового сервера')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mailing', verbose_name='Рассылки')),
            ],
            options={
                'verbose_name': 'Попытка рассылки',
                'verbose_name_plural': 'Попытки рассылок',
                'ordering': ('id',),
            },
        ),
    ]
