# Generated by Django 5.0.4 on 2024-05-13 06:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_mailing_client_alter_mailing_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientservice',
            name='email',
            field=models.EmailField(default='users.User', max_length=150, unique=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 13, 14, 4, 20, 886494), verbose_name='Дата и время отправки рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.messagemailing', verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='period_mailing',
            field=models.CharField(choices=[('Раз в день', 'Раз в день'), ('Раз в неделю', 'Раз в неделю'), ('Раз в месяц', 'Раз в месяц')], default='Раз в день', max_length=50, verbose_name='Периодичность рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status_mailing',
            field=models.CharField(choices=[('Создана', 'Создана'), ('Запущена', 'Запущена'), ('Завершена', 'Завершена')], default='Создана', max_length=50, verbose_name='Статус рассылки '),
        ),
    ]
