# Generated by Django 5.0.4 on 2024-05-13 07:52

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_clientservice_owner_alter_mailing_create_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientservice',
            name='email',
            field=models.EmailField(max_length=150, unique=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='clientservice',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 13, 15, 52, 37, 855745), verbose_name='Дата и время отправки рассылки'),
        ),
    ]
