# Generated by Django 5.0.4 on 2024-05-13 08:03

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_clientservice_email_alter_clientservice_owner_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientservice',
            name='owner',
        ),
        migrations.AddField(
            model_name='clientservice',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользватель'),
        ),
        migrations.AddField(
            model_name='mailing',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользватель'),
        ),
        migrations.AddField(
            model_name='messagemailing',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользватель'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 13, 16, 3, 52, 290481), verbose_name='Дата и время отправки рассылки'),
        ),
    ]
