# Generated by Django 5.0.4 on 2024-05-13 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_clientservice_owner_clientservice_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 13, 19, 10, 24, 33597), verbose_name='Дата и время отправки рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status_mailing',
            field=models.CharField(choices=[('Создана', 'Создана'), ('Запущена', 'Запущена'), ('Завершена', 'Завершена')], default='Создана', max_length=50, verbose_name='Статус рассылки'),
        ),
        migrations.AlterField(
            model_name='mailingattempt',
            name='date_last_mailing',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время последней рассылки'),
        ),
        migrations.AlterField(
            model_name='mailingattempt',
            name='server_response',
            field=models.CharField(blank=True, null=True, verbose_name='Ответ сервера'),
        ),
    ]
