# Generated by Django 5.0.4 on 2024-05-16 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_mailing_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 16, 20, 10, 26, 234614), verbose_name='Дата и время отправки рассылки'),
        ),
    ]
